## 2.3

### Exercise

#### Q6

In [1]:
import torch

A = torch.arange(6).reshape(3, 2)
# A / A.sum(axis=1)  # will be error, should add keepdims=True 
A / A.sum(axis=1, keepdim=True)  # find that it is normalization for row

tensor([[0.0000, 1.0000],
        [0.4000, 0.6000],
        [0.4444, 0.5556]])

#### Q10

In [2]:
A = torch.randn(1<<10, 1<<16)
B = torch.randn(1<<16, 1<<5)
C = torch.randn(1<<5, 1<<14)

In [3]:
A @ (B @ C)  # 2^35 + 2^40 (Fun fact: runtime 3.7s in cpu, much faster than I had imagined.)

tensor([[ 1798.4674,  -547.0901,  2284.9817,  ...,   333.5323,  -259.9808,
          1470.6218],
        [ -465.3961, -1639.9550, -1593.8250,  ...,   922.5110, -3461.0571,
          -406.2764],
        [-3594.0918,  1695.7753, -2225.9092,  ...,   890.1026,  1607.6746,
          1526.9343],
        ...,
        [  739.9556,  -456.0863,  -172.1988,  ...,  -889.9661,   822.1874,
         -1899.8687],
        [  669.1415,  -122.6408,   233.8080,  ..., -1790.2273, -3587.6804,
           458.2930],
        [ -641.5204,  -500.7033,   184.3544,  ...,   286.9435, -1610.8953,
           910.6255]])

In [4]:
(A @ B) @ C  # 2^31 + 2^29

tensor([[ 1798.4667,  -547.0901,  2284.9810,  ...,   333.5338,  -259.9813,
          1470.6218],
        [ -465.3961, -1639.9541, -1593.8242,  ...,   922.5115, -3461.0574,
          -406.2766],
        [-3594.0928,  1695.7754, -2225.9092,  ...,   890.1009,  1607.6736,
          1526.9338],
        ...,
        [  739.9564,  -456.0864,  -172.1998,  ...,  -889.9652,   822.1881,
         -1899.8671],
        [  669.1412,  -122.6395,   233.8073,  ..., -1790.2281, -3587.6782,
           458.2941],
        [ -641.5199,  -500.7039,   184.3555,  ...,   286.9442, -1610.8970,
           910.6254]])

#### Q12

In [5]:
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)
D = torch.stack([A, B, C], dim=2)
assert torch.allclose(D[:, :, 1], B)